server:
  port: 3344
#测试更新
spring:
  application:
    name: cloud-config-client-更新
  cloud:
    config:
      server:
        git:
          uri: git@github.com:LGzzl/cloudConfigCenter.git
